### ISSUE TITLE
Index File

### ISSUE THREAD

**Issue by RobLoach** [tinted-theming/tinted-builder-rust#12]
While tinted-builder-rust does process all the mustache templates, is there a method in order to create an index file for all of the templates?

For example...

```yaml
base16:
    extension: .html
    output: out

base24:
    extension: .html
    output: out
    supported-systems: [base24]

index:
    extension: .html
    output: out
    supported-systems: [index]
```

### index.mustache
```mustache
<ul>
  {{#schemes}}
    <li><a href="base16-{{name}}.html">{{name}}</a></li>
  {{/schemes}}
</ul>
```

### Result
```html
<ul>
    <li><a href="base16-dracula.html">Dracula</a></li>
    <li><a href="base16-tomorrow.html">Tomorrow</a></li>
    <!-- ... -->
</ul>
